<a href="https://colab.research.google.com/github/ErBharatdixit/MachineLearning/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word Embedding Techniques using Embedding Layer in Keras


In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("GPU devices:", tf.config.list_physical_devices('GPU'))






TensorFlow version: 2.19.0
Built with CUDA: True
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent = [
  "the cup of tea",
  "the bowl of soup",
  "the plate of rice",
  "the bottle of water",
  "the jar of honey",
  "the slice of bread",
  "the spoon of sugar",
  "the box of cereal",
  "the bag of flour",
  "the can of soda"
]

In [7]:
sent

['the cup of tea',
 'the bowl of soup',
 'the plate of rice',
 'the bottle of water',
 'the jar of honey',
 'the slice of bread',
 'the spoon of sugar',
 'the box of cereal',
 'the bag of flour',
 'the can of soda']

In [12]:
## Vocabulary size

voc_size = 500

One Hot Representation

In [13]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)
#

[[403, 122, 392, 102], [403, 297, 392, 455], [403, 260, 392, 242], [403, 373, 392, 56], [403, 217, 392, 200], [403, 13, 392, 222], [403, 464, 392, 147], [403, 484, 392, 38], [403, 310, 392, 244], [403, 278, 392, 169]]


Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
#

In [11]:
import numpy as np


In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 403 122 392 102]
 [  0   0   0   0 403 297 392 455]
 [  0   0   0   0 403 260 392 242]
 [  0   0   0   0 403 373 392  56]
 [  0   0   0   0 403 217 392 200]
 [  0   0   0   0 403  13 392 222]
 [  0   0   0   0 403 464 392 147]
 [  0   0   0   0 403 484 392  38]
 [  0   0   0   0 403 310 392 244]
 [  0   0   0   0 403 278 392 169]]


In [15]:
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size, 10))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
embedded_docs[0]

array([  0,   0,   0,   0, 403, 122, 392, 102], dtype=int32)

In [22]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[[ 0.04270853 -0.0459039  -0.03369271 -0.01403005 -0.04818194
    0.04255277  0.02777905 -0.01557302 -0.0181393   0.03753433]
  [ 0.04270853 -0.0459039  -0.03369271 -0.01403005 -0.04818194
    0.04255277  0.02777905 -0.01557302 -0.0181393   0.03753433]
  [ 0.04270853 -0.0459039  -0.03369271 -0.01403005 -0.04818194
    0.04255277  0.02777905 -0.01557302 -0.0181393   0.03753433]
  [ 0.04270853 -0.0459039  -0.03369271 -0.01403005 -0.04818194
    0.04255277  0.02777905 -0.01557302 -0.0181393   0.03753433]
  [-0.03987176 -0.01911817  0.01541573 -0.01208512  0.02119986
    0.02335303  0.04592029 -0.01293632 -0.04678714  0.04915993]
  [ 0.03625866  0.01857135 -0.04001019 -0.03514243  0.04363513
   -0.03668597 -0.0167007   0.03070403 -0.04763208  0.02070317]
  [-0.02410131  0.02013132 -0.03728702 -0.00162644  0.02753578
    0.00271065 -0.03260893 -0.0447834   0.0492802   0.04963154]
  [-0.02400131 -0.01873245 -0.0441125   0.0240255  -0.02039239
   -0.0428